---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magic-ip-assigner
  labels:
    app: magic-ip-assigner
spec:
  selector:
    matchLabels:
       app: magic-ip-assigner
  template:
    metadata:
      name: magic-ip-assigner
      labels:
        app: magic-ip-assigner
    spec:
      hostNetwork: true
      containers:
        - name: magic-ip-assigner
          image: nholuongut/kube-magic-ip-assigner:0.9.1-1.9.8
          securityContext:
            privileged: true
            capabilities:
              add: [NET_ADMIN, NET_RAW]
          env:
          - name: PORT
            value: "8200"
          - name: SELECTOR
            value: "app=apm-server"
          - name: PROTOCOL
            value: tcp
          - name: MAGIC_IP
            value: 169.254.210.210
          - name: HOST_INTERFACE
            value: cni0
          - name: VERBOSE
            # Set "0" or omit to reduce logs
            value: "1"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
